[build]
builder = "NIXPACKS"

[deploy]
startCommand = "bundle exec rails db:migrate && bundle exec rails server -p $PORT -b 0.0.0.0"
healthcheckPath = "/api/v1/health"
healthcheckTimeout = 30
restartPolicyType = "ON_FAILURE"
